//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chars {
            get {
                object obj = ResourceManager.GetObject("chars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] charslist {
            get {
                object obj = ResourceManager.GetObject("charslist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0002
        ///0081
        ///0082
        ///0083
        ///0084
        ///0085
        ///0086
        ///0087
        ///0088
        ///0089
        ///008A
        ///008B
        ///008C
        ///008D
        ///008E
        ///008F
        ///0090
        ///0091
        ///0092
        ///0093
        ///0094
        ///0095
        ///0096
        ///0097
        ///0098
        ///0099
        ///009A
        ///009B
        ///009C
        ///009D
        ///009E
        ///009F
        ///00A0
        ///00A1
        ///00A2
        ///00A3
        ///00A4
        ///00A5
        ///00A6
        ///00A7
        ///00A8
        ///00A9
        ///00AA
        ///00AB
        ///00AC
        ///00AD
        ///00AE
        ///00AF
        ///00B0
        ///00B1
        ///00B2
        ///00B3
        ///00B4
        ///00B5
        ///00B6
        ///00B7
        ///00B8
        ///00B9
        ///00BA
        ///00BB
        ///00BC
        ///00BD
        ///00BE
        ///00BF
        ///00C0
        ///00C1
        ///00C2
        ///00C3
        ///00C4
        ///00C5
        ///00C6
        ///00C7
        ///00C8
        ///00C9
        ///00CA
        ///00CB
        ///00CC
        ///00CD
        ///00CE
        ///00CF
        ///00D0
        ///00D1
        ///00D2
        ///00D3
        ///00D4
        ///00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_list_chunk_number {
            get {
                return ResourceManager.GetString("default_list_chunk_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconGroup101 {
            get {
                object obj = ResourceManager.GetObject("IconGroup101", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
